# Generated by Django 3.0.1 on 2019-12-30 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import employee.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('systemuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('number', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=256)),
                ('name_kana', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
            bases=('employee.systemuser',),
            managers=[
                ('objects', employee.models.SystemUserManager()),
            ],
        ),
    ]
